apiVersion: v1
kind: ConfigMap

metadata:
  name: dsgd-config

data:
  DSGD_FULL: "false"
  DSGD_ASYNC: "false"
  DSGD_RECORD: "true"
  DSGD_DATA_PATH: "/opt/mnt/datasets"
  DSGD_BATCH_SIZE: "500"
  DSGD_LEARNING_RATE: "1"
  DSGD_LAMBDA: "1"
  DSGD_NODE_COUNT: "10"
  DSGD_MASTER_PORT: "46746"
  DSGD_NODE_PORT: "46746"
  DSGD_MAX_EPOCHS: "10"
  DSGD_GOSSIP_INTERVAL: "200"
  DSGD_LEAKY_LOSS: "0.9"

---

kind: Service
apiVersion: v1

metadata:
  name: dsgd-master

spec:
  clusterIP: None
  selector:
    app: dsgd-master

  ports:
  - port: 4000

---

kind: Deployment
apiVersion: apps/v1

metadata:
  name: dsgd-master

spec:
  replicas: 1

  selector:
    matchLabels:
      app: dsgd-master

  template:
    metadata:
      labels:
        app: dsgd-master
    spec:
      containers:
      - name: dsgd-master
        image: zifeo/dsgd:node
        env:
        - name: DSGD_NODE_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DSGD_MASTER_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        envFrom:
        - configMapRef:
            name: dsgd-config
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "4"
            memory: "16Gi"
        volumeMounts:
          - name: mnt
            mountPath: /opt/mnt
      restartPolicy: Always
      imagePullSecrets:
        - name: hub-private

      volumes:
      - name: mnt
        persistentVolumeClaim:
          claimName: cs449g4-scratch

---

apiVersion: v1
kind: Service
metadata:
  name: dsgd-slave

spec:
  clusterIP: None
  selector:
    app: dsgd-slave

  ports:
  - port: 4000

---

apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: dsgd-slave

spec:
  serviceName: dsgd-slave
  replicas: 10
  podManagementPolicy: Parallel

  selector:
    matchLabels:
      app: dsgd-slave

  template:
    metadata:
      labels:
        app: dsgd-slave

    spec:
      containers:
      - name: dsgd-slave
        image: zifeo/dsgd:node
        env:
        - name: DSGD_NODE_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DSGD_MASTER_HOST
          value: "dsgd-master"
        envFrom:
        - configMapRef:
            name: dsgd-config
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "4"
            memory: "16Gi"
        volumeMounts:
        - name: mnt
          mountPath: /opt/mnt
      restartPolicy: Always
      imagePullSecrets:
      - name: hub-private

      volumes:
      - name: mnt
        persistentVolumeClaim:
          claimName: cs449g4-scratch

