kind: Service
apiVersion: v1

metadata:
  name: dsgd-master

spec:
  clusterIP: None
  selector:
    app: dsgd-master

  ports:
  - port: 4000

---

kind: Deployment
apiVersion: apps/v1

metadata:
  name: dsgd-master

spec:
  replicas: 1

  selector:
    matchLabels:
      app: dsgd-master

  template:
    metadata:
      labels:
        app: dsgd-master
    spec:
      containers:
      - name: dsgd-master
        image: zifeo/dsgd:node
        env:
        - name: DSGD_NODE_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DSGD_NODE_PORT
          value: "4000"
        - name: DSGD_MASTER_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DSGD_MASTER_PORT
          value: "4000"
        - name: DSGD_ASYNC
          value: "false"
        - name: DSGD_RECORD
          value: "false"
        - name: DSGD_DATA_PATH
          value: "/opt/mnt/datasets"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "4"
            memory: "16Gi"
      restartPolicy: Always
      imagePullSecrets:
        - name: hub-private

---

apiVersion: v1
kind: Service
metadata:
  name: dsgd-slave

spec:
  clusterIP: None
  selector:
    app: dsgd-slave

  ports:
  - port: 4000

---

apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: dsgd-slave

spec:
  serviceName: dsgd-slave
  replicas: 3
  podManagementPolicy: Parallel

  selector:
    matchLabels:
      app: dsgd-slave

  template:
    metadata:
      labels:
        app: dsgd-slave

    spec:
      containers:
      - name: dsgd-slave
        image: zifeo/dsgd:node
        env:
        - name: DSGD_NODE_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: DSGD_NODE_PORT
          value: "4000"
        - name: DSGD_MASTER_HOST
          value: "dsgd-master"
        - name: DSGD_MASTER_PORT
          value: "4000"
        - name: DSGD_ASYNC
          value: "false"
        - name: DSGD_RECORD
          value: "false"
        - name: DSGD_DATA_PATH
          value: "/opt/mnt/datasets"
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "4"
            memory: "16Gi"
        volumeMounts:
        - name: mnt
          mountPath: /opt/mnt
      restartPolicy: Always
      imagePullSecrets:
      - name: hub-private

      volumes:
      - name: mnt
        persistentVolumeClaim:
          claimName: cs449g4-scratch

