kind: Service
apiVersion: v1

metadata:
  name: influxdb

spec:
  clusterIP: None
  selector:
    app: influxdb

  ports:
  - protocol: TCP
    port: 8086
    targetPort: 8086

---

kind: Deployment
apiVersion: apps/v1

metadata:
  name: influxdb

spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb

  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - name: influxdb
        image: influxdb:1.5-alpine
        imagePullPolicy: Always
        env:
        - name: INFLUXDB_DB
          value: "db"
        - name: INFLUXDB_ADMIN_USER
          value: "root"
        - name: INFLUXDB_ADMIN_PASSWORD
          value: "secret"
      restartPolicy: Always

---

kind: Deployment
apiVersion: apps/v1

metadata:
  name: grafana

spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana

  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: zifeo/dsgd:grafana
        imagePullPolicy: Always
      restartPolicy: Always
      imagePullSecrets:
        - name: hub-private

---

kind: Deployment
apiVersion: apps/v1

metadata:
  name: chronograf

spec:
  replicas: 1
  selector:
    matchLabels:
      app: chronograf

  template:
    metadata:
      labels:
        app: chronograf
    spec:
      containers:
      - name: chronograf
        image: chronograf:1.5-alpine
        imagePullPolicy: Always
        command:
        - chronograf
        - --influxdb-url=http://influxdb:8086
        - --influxdb-username=root
        - --influxdb-password=secret
      restartPolicy: Always

